kind: PersistentVolume
apiVersion: v1
metadata:
  name: wirecloud-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #change this
    path: "/mnt/wirecloud/wirecloud_data/"