kind: PersistentVolume
apiVersion: v1
metadata:
  name: wirecloud-static
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
  #change this according to you
    path: "/mnt/wirecloud/wirecloud_static/"