apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wirecloud-static
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
