apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-conf
        - mountPath: /var/www/static
          name: nginx-wirecloud-static
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
           name: nginx-conf
           items:
            - key: nginx.conf
              path: nginx.conf
      - name: nginx-wirecloud-static
        persistentVolumeClaim:
          claimName: nginx-wirecloud-static
          readOnly: true
status: {}