apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.index.max_result_window=50000
        image: elasticsearch:2.4
        name: elasticsearch
        ports:
            - containerPort: 9200
        resources: {}
status: {}
