apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30920  