kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
  #change this
    path: "/mnt/wirecloud/postgres/"
